### ISSUE TITLE
Phase information(6th index in State) for TRADE is not as per the Documentation

### ISSUE THREAD

**Issue by srkaysh** [SanjayThomas/Monopoly#12]
Whenever Trades are proposed, the additional information field is supposed to have 5 elements i.e
True/False, Cash offered, Properties offered, Cash Requested, Properties requested.
But below are the issues found in it:

- Agent 1 : the STATE passed to 'RespondTrade' function does not contain the 'True/False' value, it just has the other 4 elements
example - `(75, [], 0, [12])`

- Agent 2 : 'RespondTrade' is called twice by the adjudicator and in the 1st call 'True/False' is not present but in the 2nd call, all 5 elements are present.
example - `(75, [], 0, [12])`, `(False, 75, [], 0, [12])`

**Comment by SanjayThomas** [comment]
Have committed the fix for the same.
Please note the new flow:
If agentOne starts the trade,
TradeResponse will be called once on agentTwo. The payload will be of the form : (75, [], 0, [12])
[Since it doesnt make sense for the true/false variable to be passed here.]

Afterwards, a receiveState called is made to agentOne. It will have the payload: (False, 75, [], 0, [12])

Keeping issue open till filer is satisfied.
